name: ac_dikari
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # ← tambah ini
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  google_sign_in: ^6.2.1
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  http: ^1.2.1
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  intl: ^0.20.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_acd.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_acd.png
