// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bSH5y9Gy9FBbtqbP5gYa36eStozkbR8',
    appId: '1:461868507755:android:989873b4eee2c0b5c4c72e',
    messagingSenderId: '461868507755',
    projectId: 'acdikari-17e8e',
    storageBucket: 'acdikari-17e8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDwylvS20iV6y_lGfQXXpyze_ljHGCqIY',
    appId: '1:461868507755:ios:13ad269c549af16ac4c72e',
    messagingSenderId: '461868507755',
    projectId: 'acdikari-17e8e',
    storageBucket: 'acdikari-17e8e.firebasestorage.app',
    androidClientId: '461868507755-h7ah2tlqkptooameoq424vug27ade81q.apps.googleusercontent.com',
    iosClientId: '461868507755-ttur4btum7bceh87p7lk17753gtg9fap.apps.googleusercontent.com',
    iosBundleId: 'com.acdikari.app',
  );
}
